### ISSUE TITLE
Source URL for PAM

### ISSUE THREAD

**Issue by montagdude** [Dlackware/pam#1]
FYI, I've been trying to build dlackware the last few days and it fails while trying to download pam-redhat-0.99.11.tar.bz2 from hashbangbash.com. The site seems to be down, I don't know if permanently or not. I found it instead at this URL, and now the build is working:

http://pkgs.fedoraproject.org/repo/pkgs/pam/pam-redhat-0.99.11.tar.bz2/29eab110f57e8d60471081a6278a5a92/pam-redhat-0.99.11.tar.bz2

**Comment by belka-ew** [comment]
Would you mind to make a pull request against master? I'll merge it then into `3.22/14.2` aswell.

**Comment by montagdude** [comment]
Sure, once I get my computer up and running again. I managed to mess up my system trying to install dlackware (my fault, not dlackware's), and I will have to do a fresh install.

**Comment by belka-ew** [comment]
I got some time and updated the URL.
Please report any issues and problems with installation. It would help a lot to improve the build scripts and documentation.
